---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
```


```{r}
cbbdata::cbd_login(username = "Naki", password = "Duke@123")
```

```{r}


team_names <- c("North Dakota St.", "Charleston", "Charlotte", "Tennessee", "Nebraska",
                "Oregon St.", "Seattle")

# Fetch all data for the specified year
online_data <- cbbdata::cbd_torvik_game_stats(year = 2025)

# Filter for the specified date
required_data <- online_data |>
  filter(date == as.Date("2024-12-23"))
print(required_data)
```

```{r}
# Prepare team data
team_data <- required_data |>
  filter(team %in% team_names) |>
  select(date, location, team, opp, adj_o, adj_d, off_efg, off_to, off_or, off_ftr,
         def_efg, def_to, def_or, def_ftr) |>
  rename(
    Location = location,
    Team = team,
    Opponent = opp,
    ADJO = adj_o, ADJD = adj_d,
    `EFG%` = off_efg, `TO%` = off_to,
    `OR%` = off_or, FTR = off_ftr,
    `Opp EFG%` = def_efg, `Opp TO%` = def_to,
    `Opp OR%` = def_or, `Opp FTR` = def_ftr
  ) |>
  mutate(
    Location = case_when(
      Location == "N" ~ "Neutral",
      Location == "H" ~ "Home",
      Location == "A" ~ "Away",
      TRUE ~ Location
    )
  )

# Prepare opponent data
opponent_data <- required_data |>
  filter(opp %in% team_names) |>
  select(date, team, opp, adj_o, adj_d) |>
  rename(
    Opponent = team,
    Team = opp,
    opp_adj_o = adj_o,
    opp_adj_d = adj_d
  )

# Join team_data and opponent_data
final_data <- team_data |>
  left_join(opponent_data, by = c("date", "Team", "Opponent"))

# Print results
print(team_data)
print(opponent_data)
print(final_data)

```

```{r}
current_file <- "basketball_games_data.csv"
old_file <- "basketball_games_dataOld.csv"

# Read the CSV file into a data frame
current_data <- read.csv(current_file)

# Append new data to the CSV file
write.table(
  current_data,
  file = old_file,
  sep = ",",
  row.names = FALSE,
  col.names = FALSE,  # Prevent column names from being written again
  append = TRUE
)

write.csv(final_data, current_file, row.names = FALSE)
```


