---
title: "R Notebook"
output: html_notebook
---

### Loading Packages
```{r}
library(dplyr)

current_date <- as.Date("2024-12-29")
file_to_write <- "test_file_29th.csv"
```


```{r}
cbbdata::cbd_login(username = "Naki", password = "Duke@123")
```

```{r}
data <- cbbdata::cbd_torvik_team_factors(year = 2025, no_bias = TRUE) 
print(data)
```

## Extract ACC and B10 Teams from list
```{r}
# Filter teams in ACC and B10 and extract into separate lists
acc_teams <- data |>
  filter(conf == "ACC") |>
  pull(team) # Extract the 'team' column as a list

b10_teams <- data |>
  filter(conf == "B10") |>
  pull(team) # Extract the 'team' column as a list

b12_teams <- data |>
  filter(conf == "B12") |>
  pull(team) # Extract the 'team' column as a list

espn_top25_week8 <- c(
  "Tennessee", "Auburn", "Iowa St.", "Duke", "Alabama", "Florida", 
  "Kansas", "Marquette", "Oregon", "Kentucky", "Connecticut", "Oklahoma", 
  "Texas A&M", "Gonzaga", "Houston", "Mississippi", "Cincinnati", 
  "Michigan St.", "Mississippi St.", "San Diego St.", 
  "Purdue", "UCLA", "Arkansas", "Illinois", "Baylor"
)

extra_games <- c("Colorado St.", "Georgia St.", "North Carolina Central", 
                 "Iowa St.", "Richmond", "Boise St.", "Nevada", "Eastern Kentucky", 
                 "Iona", "Texas St.", "Army", "Northeastern", "Northwestern")

unique_teams <- unique(c(acc_teams, b10_teams, b12_teams, espn_top25_week8, extra_games))

print(acc_teams)
print(b10_teams)
print(b12_teams)
print(espn_top25_week8)
print(unique_teams)
```

## Extract Relevant Factors
```{r}
selected_data_columns <- data |> 
  dplyr::select(Team = team, 
                ADJO = adj_o, 
                ADJD = adj_d,
                EFG_pct = efg, 
                TO_Pct = tov_rate, 
                OR_Pct = oreb_rate,
                FTR_Pct = ftr, 
                ThreePointer_Pct = three_pt_pct)

print(selected_data_columns)
```

## CLeaning Season Schedule
```{r}
all_games <- cbbdata::cbd_torvik_season_schedule(year = 2025)
all_games <- all_games |>
  mutate(Location = ifelse(neutral, "N", "H")) |>
  select(-neutral, -type, -year, -game_id) |>
  rename(Team = home,
         Opponent = away,
         )
```

## Finding Teams for a particular date

```{r}
upcoming_games <- all_games |>
  filter(date == current_date)
print(upcoming_games)

required_upcoming_games <- upcoming_games |>
  filter(Team %in% unique_teams | Opponent %in% unique_teams)
print(required_upcoming_games)
```
```{r}
# Extract stats for Team and Opponent
team_data <- required_upcoming_games |>
  left_join(selected_data_columns, by = c("Team" = "Team"))

opponent_data <- required_upcoming_games |>
  left_join(selected_data_columns, by = c("Opponent" = "Team")) |>
  rename_with(~ paste("Opp_", ., sep = ""))

# Remove unwanted columns
opponent_data <- opponent_data |>
  rename(Opponent = Opp_Opponent,
         Team = Opp_Team) |>
  select(-c("Opp_date","Opp_Location"))

# Combine both datasets
final_data <- team_data |>
  left_join(opponent_data, by = c("Team", "Opponent"))

# Print the final result
print(final_data)
```

```{r}
write.csv(final_data, file_to_write, row.names = FALSE)
```
